---
output:
  pdf_document:
    keep_tex: false
    fig_caption: yes
    latex_engine: pdflatex
    template: /Users/jesse/Dropbox/home/templates/svm-latex-syllabus.tex
bibliography: /Users/jesse/Dropbox/home/library.bib
biblio-style: authordate1
geometry: margin=1in

title: "EKT 816: Econometrics"
author: Jesse Naidoo
date: "Semester ???, 2019"

email: "jesse.naidoo@up.ac.za"
# web: "svmiller.com/teaching"
officehours: "???"
office: "Tukkiewerf 2-23"
classroom: "Tukkiewerf 1-37"
classhours: "???"

fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.05}
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, dev='pdf')
mon <- as.Date("2019-02-04")
# fri <- as.Date("2016-01-08")

advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri)
 return(tmp)
}

library(RefManageR)
# library(knitcitations)
# library(rcrossref)
bib <- ReadBib("~/Dropbox/home/library.bib")
myopts <- BibOptions(bib.style = "authoryear", style="latex", first.inits=FALSE, max.names = 20)

```

# Course Description

This is a graduate course in econometrics. Our goal is to learn some basic techniques that economists use to establish causal claims. An immediate payoff is that you will be able to read and evaluate empirical research. You may also find these methods useful in your own work.

# Required Texts

# Assessment
There will be 8 problem sets, a take-home exam, and a midterm (also take-home).

# Class Schedule

Please read at least the prescribed readings before class, even if you find it hard to follow everything; it makes for a more productive discussion if you have figured out the easy stuff first.

You may find it helpful to pattern your notes on the readings after a referee report; @Berk2017 and @Berk2015 is a useful guide to the requirements of this important type of professional communication.

## `r advdate(mon, 1)`: Probability and Statistics Review; Introduction to R
Distributions, expectations, quantiles. Laws of large numbers and the central limit theorem. Estimation: mean square error vs bias. Sufficient and ancilliary statistics.

## `r advdate(mon, 2)`: Probability and Statistics Review (continued)
Consistency and precision in estimation. Weighting and sample design. Identification. Hypothesis testing: size vs power.

## `r advdate(mon, 3)`: Counterfactuals and Causal Inference
Potential outcomes notation. Randomization delivers the ATE; brief aside on SUTVA, peer effects and general equilibrium.   Examples of causal claims.  Internal and external validity, and the value of understanding mechanisms. The importance of a clear research design. Another aside on partial identification and "structural estimation". Prediction vs causation.

_Required Readings_

- @Angrist1999
- @Heckman1995; @Card2011; @Aron-Dine2012; @Muralidharan2017b
- @Angrist2010a; @Keane2010; @Keane2010a
- @Goldberger1972
- @Imbens2009b
- @Heckman2007
- @Heckman2010e

_Optional Readings_

- @Acemoglu2010
- @Heckman2008c; @Sims2010;
- @Deaton2010; @Imbens2010
- @Manski1995
- @Mullainathan2017

## `r advdate(mon, 4)`: Linear Regression
Derivation of the OLS formula; Frisch-Waugh-Lovell theorem. Implications for interpreting regression output. Conditional expectations and best linear predictors. Typical violations of conditional independence: simultaneity, measurement error, self-selection. Applications: growth accounting and labor market discrimination.

_Required Readings_

- @Meyer2015; @Griliches1986a
- @Neal1996
- @Altonji1999
- @Topel1999; @Barro1999
- @Bazzi2013

## `r advdate(mon, 5)`: Matching and Inverse Probability Weighting
Basic similarities between matching and regression: matching methods aim for unweighted averages of treatment-control differences, while regression weights by the variance of $P(D = 1|X)$. Applications to the evaluation of job training programs.

_Required Readings_

- @Kline2011; see also the slides on Kline's website.
- @Dehejia1999; @Dehejia2002
- @Smith2005; @Dehejia2005a
- @Imbens2015
- @Solon2015

_Optional Readings_

- @LaLonde1986; @LaLonde1995
- @Heckman1999a

## `r advdate(mon, 6)`: Instrumental Variables with Homogenous Treatment Effects
Just-identified IV; 2SLS and GMM. Identification and (asymptotic) inference. Applications to the effects of Catholic schooling, the effects of childbearing on labor supply, and the returns to education.

_Required Readings_

- @Neal1997; @Altonji2005; @Angrist2001
- @Oster2017
- @Angrist1990; @Angrist1998

_Optional Readings_

- @Heckman2006a
- @Card1999; @Card2001

## `r advdate(mon, 7)`: Weak Instruments; GMM; Selection Models (Part I)


_Required Readings_

- @Bound1995
- @Stock2010
- @Andrews2018
- @Eisenhauer2015a

## `r advdate(mon, 8)`: Autumn Break
No class; I will post a take-home midterm before the break.

## `r advdate(mon, 9)`: Selection Models (Part II); Marginal Treatment Effects, LATE, and "Monotonicity"


_Required Readings_

- @Heckman2006c
- @Heckman2007b
- @Kline2019


_Optional Readings_

- @Chyn2018
- @Mueller-Smith2015
- @Arnold2018

## `r advdate(mon, 10)`: Applications; MTEs and LATE in Practice


_Required Readings_

- @Cornelissen2016
- @Wooldridge2015

_Optional Readings_

- @Bazzi2017
- @Llull2018
- @Cornelissen2018
- @Amiti2012
- @Carneiro2011

## `r advdate(mon, 11)`: Synthetic Panels and Diff-in-Diff

_Required Readings_

- @Garthwaite2014
- @Kearney2015; @Jaeger2018; @Kahn-Lang2018
- @Goodman-Bacon2018
- @Cameron2015
- @Abadie2017

_Optional Readings_

- @Hornbeck2010; @Hornbeck2014
- @Malkova2018
- @Duflo2001
- @Cunningham2018
- @Muralidharan2017a

## `r advdate(mon, 12)`: Individual-Level Panel Data (Part I)

_Required Readings_

- @Ashenfelter1985
- @MaCurdy1981
- @Jacobson1993
- @Griliches1986

_Optional Readings_

- @Diamond2018
- @Macurdy2007
- @Topel1991; @Acemoglu1999

## `r advdate(mon, 13)`: Individual-Level Panel Data, Part II - Mover Designs

_Required Readings_

- @Finkelstein2016; @Finkelstein2018b
- @Hull2018a

_Optional Readings_

- @Abowd1999; @Borovickova2017; @Song2018
- @Heckman2018

## `r advdate(mon, 14)`: Individual-Level Panel Data, Part III - Event Studies

_Required Readings_

- @Kleven2018
- @Abraham2018
- @Borusyak2016
- @Schulhofer-Wohl2018

_Optional Readings_

- @Allcott2018
- @Lagakos2018a; @Lagakos2018; @Hendricks2002; @Hendricks2018
- @Fama1969
- @Atkin2016
- @Atkin2018

## `r advdate(mon, 15)`: Discussion of Applied Papers

## `r advdate(mon, 16)`: Discussion of Applied Papers


# References
