---
output:
  pdf_document:
    keep_tex: false
    fig_caption: yes
    latex_engine: pdflatex
    template: /Users/jnaidoo/Dropbox/office/templates/svm-latex-syllabus.tex
bibliography: /Users/jnaidoo/Dropbox/office/library.bib
biblio-style: authordate1
geometry: margin=1in

title: "EKT 816: Econometrics"
author: Jesse Naidoo
date: "Semester 1, 2019"

email: "jesse.naidoo@up.ac.za"
# web: "svmiller.com/teaching"
officehours: "TBD"
office: "Tukkiewerf 2-23"
classroom: "Tukkiewerf 1-37"
classhours: "Wednesday 16.00 - 19.00"

fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.05}
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, dev='pdf')
mon <- as.Date("2019-02-04")
# fri <- as.Date("2016-01-08")

advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri)
 return(tmp)
}

library(RefManageR)
# library(knitcitations)
# library(rcrossref)
bib <- ReadBib("~/Dropbox/office/library.bib")
myopts <- BibOptions(bib.style = "authoryear", style="latex", first.inits=FALSE, max.names = 20)

```

# Course Description

This is a graduate course in econometrics. Our goal is to learn some basic techniques that economists use to establish causal claims. An immediate payoff is that you will be able to read and evaluate empirical research. You may also find these methods useful in your own work.

## Prerequisites
You need a working knowledge of calculus and linear algebra. Previous exposure to statistics will be very helpful.

## Advice

You may find it helpful to pattern your notes on the applied readings after a referee report; @Berk2017 and @Berk2015 is a useful guide to the requirements of this important type of professional communication. For the methodological or theoretical parts of the course, work through the arguments or proofs to try to convince yourself of why they are true (or find exactly why you disagree).

As with EKN-812 (or indeed any graduate course), forming study groups often has high payoffs, so I encourage you to work together.

# Required Texts
There are two required texts:

- @Angrist2008 
- @Wickham2017

@Wickham2017 is available free online, so you shouldn't buy it. A few copies of @Angrist2008 are available at the campus bookstore; I haven't checked at the off-campus ones. You may also find it useful to refer to these texts:

- @Stachurski2016
- @Wooldridge2010
- @Deaton1997
- @Cameron2005
- @Paarsch2016

Of these, @Deaton1997 is available for free in PDF format from [the World Bank's website](http://documents.worldbank.org/curated/en/593871468777303124/The-Analysis-of-Household-Surveys-A-Microeconometric-Approach-to-Development-Policy), and Stachurski has posted many lecture slides and other supporting materials to his [website](http://johnstachurski.net/emet.html). Although we will not refer explicitly to @Paarsch2016 often, it will be useful for the computational parts of the course (and indeed for those parts of your own research that require computation). 

Other than @Wickham2017, I have asked the library to place these on reserve.

# Assessment
There will be 6 problem sets, a take-home exam, and a midterm (also take-home).

# Class Schedule

Please read at least the prescribed readings before class, even if you find it hard to follow everything; it makes for a more productive discussion if you have figured out the easy stuff first.

## `r advdate(mon, 1)`: Probability and Statistics Review; Introduction to R
Distributions, expectations, quantiles. Laws of large numbers and the central limit theorem. Estimation: mean square error vs bias. 

_Required Readings_

- @Wickham2017, Ch. 3-6; 8; 26-30

_Practicals:_ Basic data manipulation in the tidyverse. R Markdown. github setup and workflow.

## `r advdate(mon, 2)`: Probability and Statistics Review (continued)
Sufficient and ancilliary statistics. Consistency and precision in estimation. Weighting and sample design. Identification. Hypothesis testing: size vs power.

_Required Readings_

- @Wickham2017, Ch. 17-21

_Practicals:_ Pipes, iteration. Monte Carlo simulations.

## `r advdate(mon, 3)`: Counterfactuals and Causal Inference
Potential outcomes notation. Randomization delivers the ATE; brief aside on SUTVA, peer effects and general equilibrium. Examples of causal claims. Internal and external validity, and the value of understanding mechanisms. 

_Required Readings: Experimental and Quasi-Experimental Approaches to Policy Evaluation_

- @Angrist2008, Ch. 1-2
- @Angrist2010a
- @Imbens2009b
- @Heckman1995
- @Heckman2010e

_Required Readings: Social Experiments in Practice_

- @Card2011
- @Aron-Dine2012
- @Muralidharan2017b

_Optional Readings: "Structural" and "Design-Based" Approaches to Econometrics_

- @Angrist1999; @Dinardo2011
- @Heckman2008c; @Heckman2007
- @Goldberger1972
- @Acemoglu2010
- @Keane2010; @Keane2010a
- @Sims2010
- @Chetty2009; @Weyl2019

_Optional Readings: Partial Identification; Prediction vs. Causation_

- @Manski1995
- @Mullainathan2017

## `r advdate(mon, 4)`: Linear Regression
Derivation of the OLS formula; Frisch-Waugh-Lovell theorem. Implications for interpreting regression output. Conditional expectations and best linear predictors. Typical violations of conditional independence: simultaneity, measurement error, self-selection. Applications: growth accounting and labor market discrimination.

_Required Readings: Regression Mechanics_

- @Angrist2008, Ch. 3 

_Required Readings: Data Quality_

- @Bound2001
- @Meyer2015
- @Griliches1986a

_Optional Readings: Statistical Decompositions_

- @Fortin2011

_Optional Readings: Labor Market Discrimination_

- @Neal1996
- @Altonji1999

_Optional Readings: Growth Accounting_

- @Topel1999
- @Barro1999 
- @Hulten2010
- @Bazzi2013

## `r advdate(mon, 5)`: Matching and Inverse Probability Weighting
Basic similarities between matching and regression: matching methods aim for unweighted averages of treatment-control differences, while regression weights by the variance of $P(D = 1|X)$. Applications to the evaluation of job training programs.

_Required Readings: Connections between Regression and Matching_

- @Angrist2008, Ch. 3.5-3.8

_Required Readings: The LaLonde Controversy_

- @Kline2011; see also the slides on Kline's website.
- @Dehejia1999; @Dehejia2002
- @Smith2005; @Dehejia2005a

_Optional Readings: Matching Methods_

- @Imbens2015
- @Solon2015

_Optional Readings: Evaluation of Job Training Programs_

- @LaLonde1986; @LaLonde1995
- @Heckman1999a

## `r advdate(mon, 6)`: Instrumental Variables with Homogenous Treatment Effects
Just-identified IV; 2SLS and GMM. Identification and (asymptotic) inference. Applications to the effects of Catholic schooling, the effects of childbearing on labor supply, and the returns to education.

_Required Readings: 2SLS and Linear Probability Models_

- @Angrist2008, Ch. 4.1-4.3
- @Angrist2001

_Required Readings: Basic Applications of IV_

- @Angrist1990
- @Angrist1998

_Required Readings: The Effects of Catholic Schooling on Student Performance_

- @Neal1997
- @Altonji2005
- @Oster2017

_Optional Readings: Supply and Demand in the Fulton Fish Market_

- @Angrist2000
- @Graddy2006

_Optional Readings: Mincerian Regressions and the "Return to Schooling"_

- @Heckman2006a
- @Card1999; @Card2001

## `r advdate(mon, 7)`: Weak Instruments; GMM; Selection Models (Part I)
2SLS bias; misleading inference with weak instruments. LIML. Outcome and selection equations in the "Generalized Roy Model". Varieties of treatment effects.


_Required Readings: Weak Instruments_

- @Angrist2008, Ch. 4.6
- @Bound1995
- @Stock2010
- @Andrews2018

_Required Readings: Models of Self-Selection_

- @Heckman1990a
- @Eisenhauer2015a
- @Heckman1990

## `r advdate(mon, 8)`: Autumn Break
No class; I will post a take-home midterm before the break.

## `r advdate(mon, 9)`: Selection Models (Part II); Marginal Treatment Effects and LATE
What does IV estimate under essential heterogeneity? Deriving the IV weights. Violations of "monotonicity". 

_Required Readings: IV With Heterogeneous Treatment Effects_

- @Angrist2008, Ch. 4.4-4.5

_Required Readings: Making Explicit the Implicit Economics of the LATE_

- @Heckman2006c
- @Heckman2007b

_Required Readings: The Relationship Between IV and Selection Models_

- @Kline2019
- @Das2003


_Optional Readings: Interpreting the LATE, External Validity and Mechanisms_

- @Deaton2010
- @Imbens2010

_Optional Readings: Applications to Criminal Justice Policy; "Neighborhood Effects" of Public Housing_

- @Chyn2018
- @Mueller-Smith2015
- @Arnold2018

## `r advdate(mon, 10)`: Applications; MTEs and LATE in Practice
Semiparametric approaches to control funtion estimation. Partial equivalence to IV. Richer treatment spaces: ordered and unordered selection. Applications.

_Required Readings: Computing Control Function Estimates_

- @Cornelissen2016
- @Wooldridge2015

_Optional Readings: Applications to Human Capital Investment_

- @Bazzi2017
- @Llull2018
- @Cornelissen2018
- @Carneiro2011

## `r advdate(mon, 11)`: Synthetic Panels and Diff-in-Diff
An additively separable model for $Y_0$ and the parallel trends assumption. Pitfalls: heterogeneous trends and serially correlated shocks. Placebo tests and placebo outcomes (DDD); clustering and bootstrapping standard errors.

_Required Readings: Interpreting DD_

- @Angrist2008, Ch. 5
- @Goodman-Bacon2018
- @Garthwaite2014
- @Muralidharan2017a

_Required Readings: Clustering_

- @Angrist2008, Ch. 8
- @Cameron2015
- @Abadie2017

_Required Readings: "16 and Pregnant" Controversy_

- @Kearney2015
- @Jaeger2018
- @Kahn-Lang2018

_Optional Readings: Miscellaneous Applications_

- @Hornbeck2010; @Hornbeck2014
- @Malkova2018
- @Duflo2001
- @Cunningham2018

## `r advdate(mon, 12)`: Individual-Level Panel Data (Part I)
The incidental parameters problem (again). Complications: lagged dependent variables and serial correlation. Applications to the effects of job loss on workers and life-cycle labor supply.

_Required Readings: The Effects of Job Loss_

- @Ashenfelter1985
- @Jacobson1993
- @Griliches1986

_Optional Readings: Dynamic Labor Supply; Rent Control_

- @Diamond2018
- @Topel1991
- @Acemoglu1999
- @Macurdy2007; @MaCurdy1981

## `r advdate(mon, 13)`: Individual-Level Panel Data, Part II - Mover Designs
Wide-panel vs long-panel asymptotics. Multiple unordered treatments in the selection equation. Applications to medical spending and worker-firm matching.

_Required Readings: Interpreting Mover Designs_

- @Finkelstein2016
- @Finkelstein2018b
- @Hull2018a
- @Heckman2018

_Optional Readings: Matched Worker-Firm Data_

- @Abowd1999
- @Borovickova2017
- @Song2018

## `r advdate(mon, 14)`: Individual-Level Panel Data, Part III - Event Studies
"Dynamic treatment effects" and long-panel asymptotics. Applications to local differences in retail prices and human capital accumulation over the life-cycle.

_Required Readings: Interpreting Event Studies and the Effects of Childbearing on Women's Earnings_

- @Kleven2018
- @Abraham2018
- @Borusyak2016
- @Schulhofer-Wohl2018

_Optional Readings: Using International Migration to Estimate the Returns to Human Capital_

- @Lagakos2018a
- @Lagakos2018
- @Hendricks2002
- @Hendricks2018

_Optional Readings: Effects of Entry and Exit in Retail; Persistent Tastes for Food in India_

- @Allcott2018
- @Atkin2016
- @Atkin2018

## `r advdate(mon, 15)`: Discussion of Applied Papers
Student discussion of applied papers. 

## `r advdate(mon, 16)`: Discussion of Applied Papers
Student discussion of applied papers. 

# References
